
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 72
#define YY_END_OF_BUFFER 73
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_acclist[347] =
    {   0,
       73,   70,   71,   72,    3,   70,   71,   72,    4,   71,
       72,   70,   71,   72,   57,   70,   71,   72,   64,   70,
       71,   72,   61,   70,   71,   72,   59,   70,   71,   72,
       65,   70,   71,   72,   60,   70,   71,   72,   70,   71,
       72,   62,   70,   71,   72,   41,   70,   71,   72,   42,
       70,   71,   72,   66,   70,   71,   72,   58,   70,   71,
       72,   55,   70,   71,   72,   55,   70,   71,   72,   55,
       70,   71,   72,   55,   70,   71,   72,   55,   70,   71,
       72,   55,   70,   71,   72,   55,   70,   71,   72,   55,
       70,   71,   72,   55,   70,   71,   72,   55,   70,   71,

       72,   55,   70,   71,   72,   55,   70,   71,   72,   55,
       70,   71,   72,   68,   70,   71,   72,   69,   70,   71,
       72,   67,   70,   71,   72,   70,   71,   72,   61,   70,
       71,   72,    5,   41,   70,   71,   72,    5,   42,   70,
       71,   72,   55,   70,   71,   72,    3,   54,   56,   63,
       53,   52,   46,   42,   46,   55,   55,   55,   55,   55,
       28,   55,   55,   55,   55,   55,   24,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,    2,    1,   63,
        5,    5,   42,   55,   55,   55,   55,   48,   52,   53,
       47,   45,   50,   44,   43,   55,   55,   55,   55,   55,

       55,    9,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       51,   37,   35,   38,   36,   34,   47,   48,   49,   45,
       21,   55,   55,   55,   55,   55,   18,   55,   26,   55,
       55,   55,   55,   20,   55,   55,   17,   55,   55,   55,
       22,   55,   12,   55,   55,   30,   55,   55,   55,   25,
       55,   55,   21,   55,   55,   55,   55,   55,   33,   32,
       49,   51,   55,   55,   55,   55,   29,   55,   27,   55,
       55,   55,   55,   55,   55,   55,   55,   23,   55,   55,
       55,   55,   55,   39,   55,   10,   55,   55,   55,   55,

       55,   55,   55,   31,   55,   16,   55,   55,   55,   10,
       55,   55,   55,   40,   55,   13,   55,   55,   55,   11,
       55,   14,   55,    6,   55,   55,   55,   13,   55,   55,
       55,   19,   55,    7,   55,   55,   55,   19,   55,   15,
       55,   55,   15,   55,    8,   55
    } ;

static const flex_int16_t yy_accept[248] =
    {   0,
        1,    1,    1,    2,    5,    9,   12,   15,   19,   23,
       27,   31,   35,   39,   42,   46,   50,   54,   58,   62,
       66,   70,   74,   78,   82,   86,   90,   94,   98,  102,
      106,  110,  114,  118,  122,  126,  129,  133,  138,  143,
      147,  148,  148,  149,  149,  150,  151,  152,  152,  152,
      152,  152,  152,  152,  152,  152,  153,  153,  154,  154,
      154,  154,  154,  155,  156,  157,  158,  159,  160,  161,
      163,  164,  165,  166,  167,  169,  170,  171,  172,  173,
      174,  175,  176,  177,  178,  178,  179,  179,  180,  181,
      182,  184,  185,  186,  187,  188,  189,  189,  189,  189,

      189,  189,  189,  189,  189,  189,  189,  191,  192,  192,
      193,  193,  194,  195,  196,  197,  198,  199,  200,  201,
      202,  204,  205,  206,  207,  208,  209,  210,  211,  212,
      213,  214,  215,  216,  217,  218,  219,  220,  221,  221,
      222,  222,  223,  223,  224,  225,  226,  226,  227,  227,
      229,  229,  229,  230,  231,  233,  234,  235,  236,  237,
      239,  241,  242,  243,  244,  246,  247,  249,  250,  251,
      253,  255,  256,  258,  259,  260,  262,  263,  265,  266,
      267,  268,  269,  270,  270,  271,  271,  271,  273,  274,
      275,  276,  277,  279,  281,  282,  283,  284,  285,  286,

      287,  288,  290,  291,  292,  293,  294,  294,  295,  296,
      298,  299,  300,  301,  302,  303,  304,  306,  308,  309,
      310,  312,  313,  314,  315,  316,  318,  319,  320,  322,
      324,  326,  327,  328,  330,  331,  332,  334,  336,  337,
      338,  340,  342,  343,  345,  347,  347
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    5,    1,    1,    1,    6,
        7,    8,    9,   10,   11,   12,   13,   14,   15,   16,
       16,   16,   16,   16,   16,   17,   17,   18,    1,    1,
       19,    1,    1,    1,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   29,   30,   31,   32,   33,   34,
       29,   35,   36,   37,   38,   29,   39,   40,   29,   29,
       41,    1,   42,    1,   43,    1,   44,   45,   46,   47,

       48,   49,   50,   51,   52,   29,   29,   53,   54,   55,
       56,   57,   58,   59,   60,   61,   62,   29,   63,   64,
       29,   29,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[65] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    2,    2,    2,    2,    1,    1,    2,
        2,    2,    2,    2,    2,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        1,    1,    3,    2,    2,    2,    2,    2,    2,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3
    } ;

static const flex_int16_t yy_base[253] =
    {   0,
        0,   60,  521,  597,  513,  597,  507,   64,  597,  461,
      597,  597,  597,   93,  597,  143,   72,  597,  597,    0,
       70,   61,   69,   29,   36,   70,   83,   45,   88,   90,
       96,   94,  597,  597,  597,  461,   70,  116,  154,  207,
      453,  424,  597,   96,  597,  597,  180,  370,  366,  379,
      355,   24,  351,  331,  326,  221,  238,  316,  170,  147,
        0,  311,  256,  597,    0,  120,  136,  192,  128,    0,
      138,  159,  145,  168,    0,  195,  197,  215,  188,  223,
      231,  240,  250,  247,  294,  597,  280,  597,  278,  279,
      293,  341,  248,  262,  257,  597,  304,  229,  227,  178,

      218,  210,  191,  132,  180,  128,  308,  597,  319,   56,
      323,  347,  351,    0,  249,  257,  324,  331,  349,  346,
      348,  350,  324,  349,  337,  347,  351,  356,  346,  353,
      360,  354,  359,  365,  374,  370,  384,  369,  405,  417,
      160,  597,   80,  597,  597,  597,  126,  597,   86,  597,
      428,  432,  436,  130,    0,  391,  384,  406,  426,    0,
        0,  423,  432,  421,    0,  434,    0,  439,  427,    0,
        0,  428,    0,  433,  433,    0,  443,    0,  448,  437,
      441,  444,  597,   70,  597,  101,  459,  483,  455,  448,
      459,  458,    0,    0,  467,  478,  484,  485,  476,  480,

      471,    0,  488,  480,  490,  484,   88,  597,  480,    0,
      478,  482,  489,  488,  495,  496,    0,    0,  495,  499,
        0,  497,  502,  597,  519,    0,  522,  517,    0,    0,
        0,  523,  528,    0,  529,  519,    0,    0,  525,  520,
        0,    0,  534,    0,    0,  597,  582,  584,  587,  590,
      593,   77
    } ;

static const flex_int16_t yy_def[253] =
    {   0,
      246,    1,  246,  246,  246,  246,  247,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  246,  246,  246,  249,  250,   16,  246,  251,
      246,  247,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      252,  246,  246,  246,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  249,  246,  250,  246,  250,  246,
      246,  251,   92,   92,   92,  246,  246,  246,  246,  246,

      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  252,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,   92,   92,   92,   92,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,   92,   92,   92,
       92,   92,  246,  246,  246,  246,  246,  246,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,

      248,  248,   92,   92,   92,   92,  246,  246,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,   92,
       92,   92,   92,  246,  248,  248,  248,  248,  248,  248,
      248,  248,   92,   92,   92,  248,  248,  248,  248,   92,
       92,  248,  248,   92,  248,    0,  246,  246,  246,  246,
      246,  246
    } ;

static const flex_int16_t yy_nxt[662] =
    {   0,
        4,    5,    6,    7,    4,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   17,   17,   18,   19,   20,
       20,   21,   22,   23,   24,   25,   20,   26,   20,   27,
       20,   20,   20,   28,   29,   30,   31,   20,   32,   20,
       33,   34,   35,   20,   20,   21,   22,   23,   24,   25,
       20,   26,   27,   20,   20,   20,   28,   20,   29,   30,
       31,   20,   32,   20,   36,   44,   73,   37,   74,  154,
      154,  102,   88,   38,   39,   39,   39,   89,  114,   79,
       69,   40,   45,   56,  103,   63,   63,   63,   63,   66,
       73,   74,   64,   70,   75,   59,   67,   44,   71,  224,

       72,   76,   68,   79,   69,   40,   47,   47,   47,   47,
       77,   80,  208,   66,   45,   78,   70,  207,   75,   59,
       67,   71,   83,   72,   76,   68,   81,   82,   84,   90,
       90,   90,   90,  186,   77,   80,   48,  185,   78,  184,
       49,   50,   51,  154,  154,   52,   83,   53,   54,  115,
       81,   82,   84,   55,   56,  116,   57,   57,   57,   57,
      113,  113,  113,   58,  119,   56,   59,   91,   91,   91,
       91,  183,  115,  120,   64,   60,  122,   59,  111,  116,
      111,  121,   61,  112,  112,  112,  112,   62,  119,  149,
       59,  148,  147,   47,   47,   47,   47,  120,   60,  122,

       96,   59,  146,   97,  123,  121,   61,   87,   87,   88,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,
      127,  145,  117,  118,   87,   87,   93,   97,  123,  144,
      143,  124,  125,   94,  107,  107,  107,  107,  142,   95,
      126,  108,  128,  127,  109,  117,  118,   87,   87,   56,
       93,   57,   57,   57,   57,  124,  125,   94,   64,  129,
      132,   59,   95,  130,  126,  131,  128,   56,  109,   63,
       63,   63,   63,  133,  134,  141,   64,  135,  155,   59,
       88,  136,   88,  129,  132,   59,  130,  137,  138,  131,
       56,  156,   90,   90,   90,   90,   86,  133,  134,   64,

      135,  155,   59,   59,   56,  136,   91,   91,   91,   91,
      137,  138,  139,   64,  139,  156,   59,  140,  140,  140,
      140,  107,  107,  107,  107,  110,   59,  152,  150,  152,
      110,  151,  153,  153,  153,  153,  112,  112,  112,  112,
       59,   87,   87,   88,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,  157,  151,  165,  158,   87,   87,
      112,  112,  112,  112,  113,  113,  113,  159,  160,  161,
      162,  164,  166,  167,  168,  163,  169,  157,  170,  165,
      158,   87,   87,  172,  106,  171,  173,  174,  175,  105,
      176,  159,  160,  161,  162,  164,  166,  167,  168,  163,

      169,  177,  170,  178,  179,  182,  104,  172,  171,  173,
      189,  174,  175,  176,  180,  101,  190,  181,  140,  140,
      140,  140,  100,   99,   98,  177,  178,   43,  179,  182,
      140,  140,  140,  140,  189,  191,  187,  180,  187,  190,
      181,  188,  188,  188,  188,  153,  153,  153,  153,  153,
      153,  153,  153,  192,   41,  193,  194,  195,  191,  196,
      197,  198,  199,   86,  200,  201,  202,  203,   46,  204,
      205,  206,  188,  188,  188,  188,  209,  192,  193,  210,
      194,  195,  211,  196,  197,  198,  199,  200,  201,  212,
      202,  203,  204,  205,  213,  206,  188,  188,  188,  188,

      209,  214,  210,  215,  216,  218,  211,  217,  219,  220,
       43,  221,  212,  222,   41,  223,  225,  226,  213,  227,
      246,  228,  229,  246,  230,  214,  231,  215,  216,  218,
      217,  232,  219,  220,  221,  233,  234,  222,  223,  235,
      225,  226,  236,  227,  228,  237,  229,  230,  238,  231,
      239,  240,  241,  242,  244,  232,  243,  245,  246,  233,
      234,  246,  246,  235,  246,  246,  236,  246,  246,  237,
      246,  238,  246,  246,  239,  240,  241,  242,  244,  243,
      246,  245,   42,   42,   42,   65,   65,   85,   85,   85,
       87,   87,   87,   92,   92,   92,    3,  246,  246,  246,

      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246
    } ;

static const flex_int16_t yy_chk[662] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    2,    8,   24,    2,   25,  110,
      110,   52,   37,    2,    2,    2,    2,   37,  252,   28,
       22,    2,    8,   17,   52,   17,   17,   17,   17,   21,
       24,   25,   17,   22,   26,   17,   21,   44,   23,  207,

       23,   26,   21,   28,   22,    2,   14,   14,   14,   14,
       27,   29,  186,   21,   44,   27,   22,  184,   26,   17,
       21,   23,   31,   23,   26,   21,   30,   30,   32,   38,
       38,   38,   38,  149,   27,   29,   14,  147,   27,  143,
       14,   14,   14,  154,  154,   14,   31,   14,   14,   66,
       30,   30,   32,   14,   16,   67,   16,   16,   16,   16,
       60,   60,   60,   16,   69,   39,   16,   39,   39,   39,
       39,  141,   66,   71,   39,   16,   73,   39,   59,   67,
       59,   72,   16,   59,   59,   59,   59,   16,   69,  106,
       16,  105,  104,   47,   47,   47,   47,   71,   16,   73,

       47,   39,  103,   47,   74,   72,   16,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       79,  102,   68,   68,   40,   40,   40,   47,   74,  101,
      100,   76,   77,   40,   56,   56,   56,   56,   99,   40,
       78,   56,   80,   79,   56,   68,   68,   40,   40,   57,
       40,   57,   57,   57,   57,   76,   77,   40,   57,   80,
       82,   57,   40,   81,   78,   81,   80,   63,   56,   63,
       63,   63,   63,   83,   84,   98,   63,   93,  115,   63,
       89,   94,   87,   80,   82,   57,   81,   95,   95,   81,
       90,  116,   90,   90,   90,   90,   85,   83,   84,   90,

       93,  115,   90,   63,   91,   94,   91,   91,   91,   91,
       95,   95,   97,   91,   97,  116,   91,   97,   97,   97,
       97,  107,  107,  107,  107,   62,   90,  109,  107,  109,
       58,  107,  109,  109,  109,  109,  111,  111,  111,  111,
       91,   92,   92,   92,   92,   92,   92,   92,   92,   92,
       92,   92,   92,   92,  117,  107,  123,  117,   92,   92,
      112,  112,  112,  112,  113,  113,  113,  118,  119,  120,
      121,  122,  124,  125,  126,  121,  127,  117,  128,  123,
      117,   92,   92,  129,   55,  128,  130,  131,  132,   54,
      133,  118,  119,  120,  121,  122,  124,  125,  126,  121,

      127,  134,  128,  135,  136,  138,   53,  129,  128,  130,
      156,  131,  132,  133,  137,   51,  157,  137,  139,  139,
      139,  139,   50,   49,   48,  134,  135,   42,  136,  138,
      140,  140,  140,  140,  156,  158,  151,  137,  151,  157,
      137,  151,  151,  151,  151,  152,  152,  152,  152,  153,
      153,  153,  153,  159,   41,  162,  163,  164,  158,  166,
      168,  169,  172,   36,  174,  175,  177,  179,   10,  180,
      181,  182,  187,  187,  187,  187,  189,  159,  162,  190,
      163,  164,  191,  166,  168,  169,  172,  174,  175,  192,
      177,  179,  180,  181,  195,  182,  188,  188,  188,  188,

      189,  196,  190,  197,  198,  200,  191,  199,  201,  203,
        7,  204,  192,  205,    5,  206,  209,  211,  195,  212,
        3,  213,  214,    0,  215,  196,  216,  197,  198,  200,
      199,  219,  201,  203,  204,  220,  222,  205,  206,  223,
      209,  211,  225,  212,  213,  227,  214,  215,  228,  216,
      232,  233,  235,  236,  240,  219,  239,  243,    0,  220,
      222,    0,    0,  223,    0,    0,  225,    0,    0,  227,
        0,  228,    0,    0,  232,  233,  235,  236,  240,  239,
        0,  243,  247,  247,  247,  248,  248,  249,  249,  249,
      250,  250,  250,  251,  251,  251,  246,  246,  246,  246,

      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246
    } ;

extern int yy_flex_debug;
int yy_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
++(yy_lp); \
goto find_rule; \
}

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "fort.l"
#line 2 "fort.l"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "intermediate.h"
#include "fort.tab.h"

int line_number = 1;
int in_write = 0;  /* Flag για να ξέρουμε αν είμαστε μέσα σε WRITE statement */
int in_data = 0;   /* Flag για DATA statement */
char line_buf[1024] = "";  /* Buffer για την τρέχουσα γραμμή */
int line_pos = 0;          /* Θέση στο line_buf */
int collecting_line = 1;   /* Flag για να ελέγχουμε αν συλλέγουμε γραμμή */
int error_count = 0;       /* Μετρητής λαθών */

/* Debugging function - μόνο όταν ορίζεται DEBUG */
#ifdef DEBUG
#define DEBUG_PRINT(fmt, ...) fprintf(stderr, fmt, ##__VA_ARGS__)
#else
#define DEBUG_PRINT(fmt, ...)
#endif

/* Function για αναφορά λεκτικών λαθών */
void lexical_error(const char* msg) {
    fprintf(stderr, "Lexical error at line %d: %s\n", line_number, msg);
    fprintf(stderr, "Line: %s\n", line_buf);
    fprintf(stderr, "      ");
    for(int i=0; i < line_pos-yyleng; i++) fprintf(stderr, " ");
    fprintf(stderr, "^\n");
    error_count++;
}
#line 747 "lex.yy.c"
/* Ορισμοί για αναγνώριση αριθμών σε διάφορες βάσεις */
#line 749 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in yylex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 43 "fort.l"


#line 46 "fort.l"
    /* Σχόλια - δεν αυξάνουμε το line_number εδώ γιατί θα το κάνει ο \n κανόνας */
#line 980 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 247 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 597 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];

find_rule: /* we branch to this label when backing up */

		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
					{
					(yy_full_match) = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 47 "fort.l"
{ DEBUG_PRINT("COMMENT at line %d\n", line_number); }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 48 "fort.l"
{ DEBUG_PRINT("COMMENT at line %d\n", line_number); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 49 "fort.l"
/* ignore whitespace */ ;
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 50 "fort.l"
{ DEBUG_PRINT("Line number increased from %d to %d\n", line_number, line_number + 1);
                  line_number++; }
	YY_BREAK
/* Λτικέτες */
case 5:
YY_RULE_SETUP
#line 54 "fort.l"
{ DEBUG_PRINT("LABEL(%s) at line %d\n", yytext, line_number);
                  yylval.ival = atoi(yytext); return LABEL; }
	YY_BREAK
/* Λέξεις-κλειδιά - case insensitive */
case 6:
YY_RULE_SETUP
#line 58 "fort.l"
{ DEBUG_PRINT("PROGRAM at line %d\n", line_number); return PROGRAM; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 59 "fort.l"
{ DEBUG_PRINT("FUNCTION at line %d\n", line_number); return FUNCTION; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 60 "fort.l"
{ DEBUG_PRINT("SUBROUTINE at line %d\n", line_number); return SUBROUTINE; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 61 "fort.l"
{ DEBUG_PRINT("END at line %d\n", line_number); return END; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 62 "fort.l"
{ DEBUG_PRINT("COMMON at line %d\n", line_number); return COMMON; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 63 "fort.l"
{ DEBUG_PRINT("INTEGER at line %d\n", line_number); return INTEGER; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 64 "fort.l"
{ DEBUG_PRINT("REAL at line %d\n", line_number); return REAL; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 65 "fort.l"
{ DEBUG_PRINT("COMPLEX at line %d\n", line_number); return COMPLEX; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 66 "fort.l"
{ DEBUG_PRINT("LOGICAL at line %d\n", line_number); return LOGICAL; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 67 "fort.l"
{ DEBUG_PRINT("CHARACTER at line %d\n", line_number); return CHARACTER; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 68 "fort.l"
{ DEBUG_PRINT("STRING at line %d\n", line_number); return STRING; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 69 "fort.l"
{ DEBUG_PRINT("LIST at line %d\n", line_number); return LIST; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 70 "fort.l"
{ DEBUG_PRINT("DATA token at line %d\n", line_number); in_data = 1; return DATA; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 71 "fort.l"
{ DEBUG_PRINT("CONTINUE at line %d\n", line_number); return CONTINUE; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 72 "fort.l"
{ DEBUG_PRINT("GOTO at line %d\n", line_number); return GOTO; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 73 "fort.l"
{ DEBUG_PRINT("CALL at line %d\n", line_number); return CALL; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 74 "fort.l"
{ DEBUG_PRINT("READ at line %d\n", line_number); return READ; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 75 "fort.l"
{ DEBUG_PRINT("WRITE at line %d\n", line_number); in_write = 1; return WRITE; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 76 "fort.l"
{ DEBUG_PRINT("IF at line %d\n", line_number); return IF; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 77 "fort.l"
{ DEBUG_PRINT("THEN at line %d\n", line_number); return THEN; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 78 "fort.l"
{ DEBUG_PRINT("ELSE at line %d\n", line_number); return ELSE; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 79 "fort.l"
{ DEBUG_PRINT("ENDIF at line %d\n", line_number); return ENDIF; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 80 "fort.l"
{ DEBUG_PRINT("DO at line %d\n", line_number); return DO; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 81 "fort.l"
{ DEBUG_PRINT("ENDDO at line %d\n", line_number); return ENDDO; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 82 "fort.l"
{ DEBUG_PRINT("STOP at line %d\n", line_number); return STOP; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 83 "fort.l"
{ DEBUG_PRINT("RETURN at line %d\n", line_number); return RETURN; }
	YY_BREAK
/* Λογικοί τελεστές */
case 32:
YY_RULE_SETUP
#line 86 "fort.l"
{ DEBUG_PRINT("NOT at line %d\n", line_number); return NOT; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 87 "fort.l"
{ DEBUG_PRINT("AND at line %d\n", line_number); return AND; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 88 "fort.l"
{ DEBUG_PRINT("OR at line %d\n", line_number); return OR; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 89 "fort.l"
{ DEBUG_PRINT("GT at line %d\n", line_number); return GT; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 90 "fort.l"
{ DEBUG_PRINT("LT at line %d\n", line_number); return LT; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 91 "fort.l"
{ DEBUG_PRINT("EQ at line %d\n", line_number); return EQ; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 92 "fort.l"
{ DEBUG_PRINT("LE at line %d\n", line_number); return LE; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 93 "fort.l"
{ DEBUG_PRINT("TRUE at line %d\n", line_number); return TRUE; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 94 "fort.l"
{ DEBUG_PRINT("FALSE at line %d\n", line_number); return FALSE; }
	YY_BREAK
/* Ακέραιες σταθερές */
case 41:
YY_RULE_SETUP
#line 97 "fort.l"
{ DEBUG_PRINT("ICONST(0) at line %d\n", line_number); 
                  yylval.ival = 0; return ICONST; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 99 "fort.l"
{ 
                  DEBUG_PRINT("ICONST(%s) at line %d\n", yytext, line_number);
                  yylval.ival = atoi(yytext); return ICONST; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 102 "fort.l"
{ 
                  DEBUG_PRINT("ICONST(0x%s) at line %d\n", yytext+2, line_number);
                  yylval.ival = strtol(yytext, NULL, 16); return ICONST; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 105 "fort.l"
{ 
                  DEBUG_PRINT("ICONST(0o%s) at line %d\n", yytext+2, line_number);
                  yylval.ival = strtol(yytext+2, NULL, 8); return ICONST; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 108 "fort.l"
{ 
                  DEBUG_PRINT("ICONST(0b%s) at line %d\n", yytext+2, line_number);
                  yylval.ival = strtol(yytext+2, NULL, 2); return ICONST; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 111 "fort.l"
{ yylval.ival = strtol(yytext, NULL, 2); return ICONST; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 112 "fort.l"
{ yylval.rval = strtod(yytext, NULL); return RCONST; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 113 "fort.l"
{ yylval.rval = strtod(yytext, NULL); return RCONST; }
	YY_BREAK
/* Πραγματικές σταθερές */
case 49:
#line 117 "fort.l"
case 50:
#line 118 "fort.l"
case 51:
#line 119 "fort.l"
case 52:
#line 120 "fort.l"
case 53:
YY_RULE_SETUP
#line 120 "fort.l"
{ 
    DEBUG_PRINT("RCONST(%s) at line %d\n", yytext, line_number);
    yylval.rval = atof(yytext); 
    return RCONST; 
}
	YY_BREAK
/* Strings */
case 54:
/* rule 54 can match eol */
YY_RULE_SETUP
#line 127 "fort.l"
{ DEBUG_PRINT("STRING_LITERAL(%s) at line %d\n", yytext, line_number);
                 yylval.sval = strdup(yytext+1);
                 yylval.sval[strlen(yylval.sval)-1] = '\0';
                 return STRING_LITERAL; }
	YY_BREAK
/* Αναγνωριστικά */
case 55:
YY_RULE_SETUP
#line 133 "fort.l"
{
    char *p = yytext;
    int len = strlen(p);
    int has_underscore = 0;
    int valid = 1;
    char next;

    /* Αποθήκευση του ID χωρίς το υπόλοιπο αρχείο */
    char id_buf[256];
    strncpy(id_buf, yytext, sizeof(id_buf)-1);
    id_buf[sizeof(id_buf)-1] = '\0';

    DEBUG_PRINT("DEBUG LEXER: Starting ID analysis for '%s'\n", id_buf);
    DEBUG_PRINT("DEBUG LEXER: Current line (len=%d): '%s'\n", line_pos, line_buf);
    DEBUG_PRINT("DEBUG LEXER: Position: %d\n", line_pos);
    next = input();
    DEBUG_PRINT("DEBUG LEXER: Next char will be: '%c'\n", next);
    unput(next);

    /* Έλεγχος για διαδοχικά _ και _ στο τέλος */
    for(int i = 0; i < len && i < sizeof(id_buf)-1; i++) {
        if (p[i] == '_') {
            has_underscore = 1;
            if (i < len-1 && p[i+1] == '_') {
                valid = 0;
                DEBUG_PRINT("DEBUG LEXER: Found consecutive underscores\n");
                break;
            }
        }
    }

    /* Αν έχει _ πρέπει να τελειώνει σε _ */
    if (has_underscore && p[len-1] != '_') {
        valid = 0;
        DEBUG_PRINT("DEBUG LEXER: Underscore found but not at end\n");
    }

    if (valid) {
        DEBUG_PRINT("DEBUG LEXER: Valid ID '%s' found\n", id_buf);
        DEBUG_PRINT("ID(%s) at line %d\n", id_buf, line_number);
        yylval.sval = strdup(id_buf);
        return ID;
    } else {
        DEBUG_PRINT("Lexical error at line %d: Invalid identifier '%s'\n", 
               line_number, id_buf);
        DEBUG_PRINT("Line: %s\n", line_buf);
        DEBUG_PRINT("      ");
        for(int i=0; i < line_pos-yyleng; i++) DEBUG_PRINT(" ");
        DEBUG_PRINT("^\n");
    }
}
	YY_BREAK
/* Τελεστές και σύμβολα */
case 56:
YY_RULE_SETUP
#line 186 "fort.l"
{ DEBUG_PRINT("LPAREN_ASSIGN at line %d\n", line_number); return LPAREN_ASSIGN; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 187 "fort.l"
{ DEBUG_PRINT("LPAREN at line %d\n", line_number); return LPAREN; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 188 "fort.l"
{ DEBUG_PRINT("ASSIGN at line %d\n", line_number); return ASSIGN; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 189 "fort.l"
{ DEBUG_PRINT("ADDOP(+) at line %d\n", line_number); return ADDOP; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 190 "fort.l"
{ DEBUG_PRINT("ADDOP(-) at line %d\n", line_number); return ADDOP; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 191 "fort.l"
{ 
                  DEBUG_PRINT("STAR/MULOP at line %d\n", line_number); 
                  if (in_write || in_data) {
                    DEBUG_PRINT("Treating * as STAR (in_write=%d, in_data=%d)\n", 
                           in_write, in_data);
                    return STAR;
                  } else {
                    DEBUG_PRINT("Treating * as MULOP\n");
                    return MULOP;
                  }
                }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 202 "fort.l"
{ DEBUG_PRINT("DIVOP at line %d\n", line_number); return DIVOP; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 203 "fort.l"
{ DEBUG_PRINT("POWEROP at line %d\n", line_number); return POWEROP; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 204 "fort.l"
{ DEBUG_PRINT("RPAREN at line %d\n", line_number); return RPAREN; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 205 "fort.l"
{ DEBUG_PRINT("COMMA at line %d\n", line_number); return COMMA; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 206 "fort.l"
{ DEBUG_PRINT("COLON at line %d\n", line_number); return COLON; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 207 "fort.l"
{ DEBUG_PRINT("UNDERSCORE at line %d\n", line_number); return '_'; }
	YY_BREAK
/* Χειρισμός σφαλμάτων - τώρα πιο συγκεκριμένος */
case 68:
YY_RULE_SETUP
#line 210 "fort.l"
{ lexical_error("Invalid token '['"); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 211 "fort.l"
{ lexical_error("Invalid token ']'"); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 212 "fort.l"
{ 
    char msg[100];
    snprintf(msg, sizeof(msg), "Invalid character '%s'", yytext);
    lexical_error(msg);
}
	YY_BREAK
/* Συλλογή χαρακτήρων για εκτύπωση γραμμής σε σφάλματα */
case 71:
/* rule 71 can match eol */
YY_RULE_SETUP
#line 219 "fort.l"
{
    if (collecting_line) {
        if (yytext[0] == '\n') {
            line_buf[line_pos] = '\0';
            line_pos = 0;
        } else if (line_pos < sizeof(line_buf)-1) {
            line_buf[line_pos] = yytext[0];
            line_pos++;
            line_buf[line_pos] = '\0';
        }
        collecting_line = 0;  /* Σταματάμε τη συλλογή μέχρι τον επόμενο χαρακτήρα */
        yyless(0);
    } else {
        collecting_line = 1;  /* Επανενεργοποιούμε τη συλλογή για τον επόμενο χαρακτήρα */
        /* Προωθούμε τον χαρακτήρα στον επόμενο κανόνα */
        REJECT;
    }
}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 238 "fort.l"
ECHO;
	YY_BREAK
#line 1505 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 247 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    
	YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 247 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 246);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    yyfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 238 "fort.l"


int yywrap(void) {
    return 1;
}

